/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
#include <android/log.h>
/* Header for class cn_EGGMaster_util_JniUtils */

#undef ISNET
#define ISNET 100101
#undef ALLHTTPS
#define ALLHTTPS 100102
#undef HTTP_IP
#define HTTP_IP 100111
#undef HTTP_PORT
#define HTTP_PORT 100112
#undef HTTPS_IP
#define HTTPS_IP 100121
#undef HTTPS_PORT
#define HTTPS_PORT 100122

#define LOG_TAG "ndk-test"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)

#ifndef _Included_cn_EGGMaster_util_JniUtils
#define _Included_cn_EGGMaster_util_JniUtils
#endif